name: Chess Stats Readme

on:
  push:
  schedule:
    # Runs at 12am IST
    - cron: "30 18 * * *"
jobs:
  update-readme:
    name: Update readme with chess stats
    runs-on: ubuntu-latest
    steps:
      - uses: Prathamesh-B/chess-stats-readme@master
        with:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          CHESS_USERNAME: mayannait
